version: "3.9"

services:
  flagd:
    image: ghcr.io/open-feature/flagd:latest
    container_name: flagd
    environment:
      - FLAGD_LOG_LEVEL=debug
      - FLAGD_PROVIDER_SYNC_INTERVAL=30s
      - FLAGD_PROVIDER_REQUEST_TIMEOUT=30s
    command: start --uri http://YOUR_HOST_IP:3000/flagd
